## ðŸ’¯10 minutes to pandas
This is a short introduction to pandas, geared mainly for new users. You can see more complex recipes in the [Cookbook](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html)

Customarily, we import as follows:

In [1]:
import numpy as np 
import pandas as pd

## Object creation
See the [Intro to data structures section](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html#dsintro).

Creating a `Series` by passing a list of values, letting pandas create a default integer index:

In [3]:
s = pd.Series([1,3,5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a `DataFrame` by passing a NumPy array, with a datetime index and labeled columns:

In [4]:
dates = pd.date_range("20220331", periods=6)
dates

DatetimeIndex(['2022-03-31', '2022-04-01', '2022-04-02', '2022-04-03',
               '2022-04-04', '2022-04-05'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2022-03-31  0.329825  1.157738  1.039792 -1.238610
2022-04-01 -1.294523 -1.008181  0.566901 -0.741472
2022-04-02  0.777284  0.897736 -0.002486 -0.402372
2022-04-03 -1.287733 -0.472010  0.220806 -0.824322
2022-04-04 -0.606412  1.264361 -1.508785  2.327784
2022-04-05  0.490044  0.870560 -1.525671  1.462980

Creating a `DataFrame` by passing a dictionary of objects that can be converted into a series-like structure:

In [9]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20220331"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
     }
)

df2

     A          B    C  D      E    F
0  1.0 2022-03-31  1.0  3   test  foo
1  1.0 2022-03-31  1.0  3  train  foo
2  1.0 2022-03-31  1.0  3   test  foo
3  1.0 2022-03-31  1.0  3  train  foo

The columns of the resulting `DataFrame` have different dtypes:

In [10]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

If you're using IPython, tab completion for column names (as well as public attributes) is automatically enabled. Here's a subset of the attributes that will be completed:

In [ ]:
# >>> df2.<TAB>  # noqa: E225, E999
# df2.A                  df2.bool
# df2.abs                df2.boxplot
# df2.add                df2.C
# df2.add_prefix         df2.clip
# df2.add_suffix         df2.columns
# df2.align              df2.copy
# df2.all                df2.count
# df2.any                df2.combine
# df2.append             df2.D
# df2.apply              df2.describe
# df2.applymap           df2.diff
# df2.B                  df2.duplicated

As you can see, the columns A,B,C, and D are automatically tab completed. E and F are there as well; the rest of the attributes have been truncated for brevity.

#Viewing data
See the [Basics section](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics).  
Here is how to view the top and bottom rows of the frame: